services:
  - type: web
    name: ai-wallet
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "3000"
      - key: HOSTNAME
        value: "0.0.0.0"
    healthCheckPath: /
    autoDeploy: true 